---
name: test-notify-build-status

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dependabot/**'
    paths:
      - '.github/actions/notify-build-status/**'
      - '.github/workflows/test-notify-build-status.yml'

permissions:
  contents: read

jobs:
  test-notify-build-status-wrapper:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/actions/notify-build-status
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # Must be kept in sync with node version in action.yml
          node-version-file: './.github/actions/notify-build-status/.node-version'
      - name: Install dependencies
        run: npm ci
      - name: Lint, Format, Build, Test & Package
        run: npm run all
      - name: Check nothing changes
        run: npm run check

  test-notify-build-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
          message: 'Test Github Action Notify Build Status'
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
          message: |
            Test Multiline
            Github Action Notify Build Status
      - uses: ./.github/actions/notify-build-status
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: '#observablt-bots'
